# Generated by Django 4.2 on 2023-04-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_country_querychatgpt_city_attractions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='querychatgpt',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='querychatgpt',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='querychatgpt',
            name='during_trip',
        ),
        migrations.RemoveField(
            model_name='querychatgpt',
            name='max_stop',
        ),
        migrations.RemoveField(
            model_name='querychatgpt',
            name='traveler',
        ),
        migrations.AddField(
            model_name='querychatgpt',
            name='answer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='querychatgpt',
            name='question',
            field=models.CharField(default='', max_length=500),
        ),
    ]
