# Generated by Django 4.1.8 on 2023-06-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_email_emailrequestcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='EmailRequestCount',
        ),
    ]
