# Generated by Django 4.1.8 on 2023-06-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_email_delete_emailrequestcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='querychatgpt',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='querychatgpt',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
