# Generated by Django 4.1.8 on 2023-06-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_querychatgpt_latitude_querychatgpt_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='querychatgpt',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='querychatgpt',
            name='longitude',
        ),
    ]
