# Generated by Django 4.2 on 2023-04-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_trip_remove_city_country_delete_attractions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
