# Generated by Django 4.1.8 on 2023-06-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_city_remove_querychatgpt_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='attractions',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
