# Generated by Django 4.1.8 on 2023-06-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_city_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='restaurants',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
