# Generated by Django 4.1.8 on 2023-07-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_restaurant_details_restaurant_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attraction',
            old_name='url',
            new_name='social_media',
        ),
        migrations.AddField(
            model_name='attraction',
            name='hours_popular',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attraction',
            name='price',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attraction',
            name='website',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='social_media',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
