# Generated by Django 4.1.8 on 2023-07-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_restaurant_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='price',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='social_media',
        ),
    ]
