# Generated by Django 4.1.8 on 2023-07-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_attraction_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='querychatgpt',
            name='itinerary_description',
            field=models.TextField(default=''),
        ),
    ]
