# Generated by Django 4.1.8 on 2023-07-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_querychatgpt_itinerary_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='real_price',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
