# Generated by Django 4.1.8 on 2023-07-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_attraction_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='name',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='photos',
            field=models.TextField(max_length=100),
        ),
    ]
