# Generated by Django 4.1.8 on 2023-07-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_attraction_name_alter_attraction_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='review_score',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='website',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='photos',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='review_score',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='social_media',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='website',
            field=models.TextField(max_length=100),
        ),
    ]
