# Generated by Django 4.1.8 on 2023-07-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_attraction_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='distance',
            field=models.TextField(max_length=200),
        ),
    ]
