# Generated by Django 4.1.8 on 2023-07-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_restaurant_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPTData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_restaurants', models.TextField(blank=True)),
                ('new_attractions', models.TextField(blank=True)),
            ],
        ),
    ]
