# Generated by Django 4.1.8 on 2023-07-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_gptdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attractions_to_db', models.TextField(max_length=50000)),
                ('restaurants_to_db', models.TextField(max_length=50000)),
            ],
        ),
        migrations.DeleteModel(
            name='GPTData',
        ),
    ]
