# Generated by Django 4.1.8 on 2023-07-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_new_db_delete_gptdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New_DB',
        ),
    ]
