# Generated by Django 4.1.8 on 2023-07-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_delete_new_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='real_price',
            field=models.TextField(max_length=200),
        ),
    ]
