# Generated by Django 4.1.8 on 2023-07-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_attraction_real_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='popularity_score',
            field=models.IntegerField(default=0),
        ),
    ]
