# Generated by Django 4.1.8 on 2023-07-29 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_country_popularity_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels_foursqaure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('photos', models.TextField(max_length=100)),
                ('review_score', models.TextField(max_length=20)),
                ('description', models.TextField(max_length=1000)),
                ('website', models.TextField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='app.city')),
            ],
        ),
    ]
