# Generated by Django 4.1.8 on 2023-08-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='place_id',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
