# Generated by Django 4.1.8 on 2023-08-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_hotels_foursqaure_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='adress',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='hours',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tel',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
