# Generated by Django 4.1.8 on 2023-08-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_restaurant_adress_restaurant_hours_restaurant_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='adress',
            new_name='address',
        ),
    ]
