# Generated by Django 4.1.8 on 2023-08-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_rename_adress_restaurant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='address',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='hours',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='tel',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
