# Generated by Django 4.1.8 on 2023-08-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_attraction_address_attraction_hours_attraction_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='tips',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
