# Generated by Django 4.1.8 on 2023-08-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_attraction_tips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='social_media',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tips',
            field=models.TextField(default='', max_length=3000),
            preserve_default=False,
        ),
    ]
