# Generated by Django 4.1.8 on 2023-08-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_remove_restaurant_distance_remove_restaurant_menu_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
        migrations.AddField(
            model_name='country',
            name='average_prices',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
