# Generated by Django 4.1.8 on 2023-08-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_applicationrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationrating',
            old_name='user',
            new_name='user_email',
        ),
        migrations.AddField(
            model_name='applicationrating',
            name='review',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationrating',
            name='user_name',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationrating',
            name='user_picture',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
