# Generated by Django 4.1.8 on 2023-09-22 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_rename_user_applicationrating_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(max_length=100)),
                ('trip_from_query_chat_gpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.querychatgpt')),
            ],
        ),
    ]
