# Generated by Django 4.1.8 on 2023-09-22 13:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='trip_from_query_chat_gpt',
        ),
        migrations.AddField(
            model_name='users',
            name='liked_trips',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
