# Generated by Django 4.1.8 on 2023-10-01 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_remove_users_liked_trips_usertrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrip',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertrip', to='app.users'),
        ),
    ]
