# Generated by Django 4.1.8 on 2023-10-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_alter_usertrip_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrip',
            name='liked_trips',
            field=models.TextField(default=list, verbose_name=models.IntegerField()),
        ),
    ]
