# Generated by Django 4.1.8 on 2023-10-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_usertrip_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrip',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
