# Generated by Django 4.1.8 on 2023-10-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_alter_applicationrating_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querychatgpt',
            name='answer',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='querychatgpt',
            name='itinerary_description',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='querychatgpt',
            name='question',
            field=models.CharField(default='[]', max_length=500),
        ),
    ]
