# Generated by Django 4.1.8 on 2023-10-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_alter_applicationrating_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrating',
            name='review',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicationrating',
            name='user_email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='applicationrating',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='applicationrating',
            name='user_picture',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='distance',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='hours',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='hours_popular',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='photos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='place_id',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='real_price',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='review_score',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='tel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='tips',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='website',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='average_prices',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hotels_foursqaure',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hotels_foursqaure',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='hotels_foursqaure',
            name='photos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotels_foursqaure',
            name='place_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hotels_foursqaure',
            name='review_score',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hotels_foursqaure',
            name='website',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='popular',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='popular',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='querychatgpt',
            name='answer',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='querychatgpt',
            name='itinerary_description',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='hours',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='photos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='place_id',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='review_score',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tips',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='website',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usertrip',
            name='end_trip',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usertrip',
            name='liked_trips',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usertrip',
            name='start_trip',
            field=models.CharField(max_length=100),
        ),
    ]
