# Generated by Django 4.1.8 on 2024-02-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_alter_applicationrating_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='average_food',
            field=models.TextField(default=0, max_length=200),
        ),
    ]
