# Generated by Django 4.1.8 on 2024-02-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_country_average_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='average_hotels',
            field=models.TextField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='country',
            name='average_transportation',
            field=models.TextField(default=0, max_length=200),
        ),
    ]
