# Generated by Django 4.1.8 on 2024-02-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_country_average_hotels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckNewAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('photos', models.TextField(max_length=100)),
                ('review_score', models.TextField(max_length=20)),
                ('description', models.TextField(max_length=1000)),
                ('real_price', models.TextField(max_length=200)),
                ('website', models.TextField(max_length=100, null=True)),
                ('hours_popular', models.TextField(null=True)),
                ('distance', models.TextField(max_length=200, null=True)),
                ('hours', models.TextField(max_length=150, null=True)),
                ('tel', models.TextField(max_length=100, null=True)),
                ('address', models.TextField(max_length=100, null=True)),
                ('place_id', models.TextField(max_length=150, null=True)),
                ('tips', models.TextField(max_length=3000, null=True)),
            ],
        ),
    ]
