# Generated by Django 4.1.8 on 2024-02-06 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_checknewattraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='checknewattraction',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='addnewattractions', to='app.city'),
            preserve_default=False,
        ),
    ]
