

[
    {'name': 'Palatial Gardens below Prague Castle (Palácové zahrady pod Pražským hradem)', 'distance': 'On the hill below Prague Castle, in the city center'},
    {'name': 'Santorini Camping', 'distance': 'Located in southern part of Santorini island, near Perissa'}, 
    {'name': 'Aarhus SeaRangers', 'distance': 'Meet at the harbor in Aarhus city center'},
    {'name': 'Inge Lehmann', 'distance': 'Statue located in central Copenhagen'},
    {'name': 'Reykjavíkurtjörn', 'distance': 'Pond located in Reykjavik city center'},
    {'name': 'MoMu - Fashion Museum Antwerp', 'distance': 'Located in Antwerp city center'},
    {'name': 'Prague Castle View Point (Vyhlídka na Hradčanském náměstí)', 'distance': 'Located in Prague Castle complex, city center'},
    {'name': 'Heidelberger Schloss', 'distance': 'Located above old town in Heidelberg city center'},
    {'name': 'Kijk In 'T Jat Brug', 'distance': 'Museum located in Bruges city center'},
    {'name': 'Denarau Golf and Racquet Club', 'distance': 'Located on Denarau Island by Nadi town'},
    {'name': 'Helsinki Sightseeing', 'distance': 'Boat tours leave from Helsinki city center harbor'}, 
    {'name': 'Macritchie Nature Trail', 'distance': 'Located within MacRitchie Reservoir Park in Singapore'},
    {'name': 'Bukit Timah Nature Reserve', 'distance': 'Located 10 km from Singapore city center'},
    {'name': 'Moderna Museet', 'distance': 'Museum located on Skeppsholmen island, central Stockholm'},
    {'name': 'Fotografiska', 'distance': 'Museum located in Södermalm district of Stockholm'},
    {'name': 'Várnegyed', 'distance': 'Section of Buda Castle complex in Budapest city center'},
    {'name': 'Filozófusok kertje', 'distance': 'Garden located within Budapest University campus'},
    {'name': 'Várkert Bazár', 'distance': 'Located below Buda Castle hill in Budapest center'},
    {'name': 'Park Kultury im. marszałka Edwarda Śmigłego-Rydza', 'distance': 'Park located in Lublin city center'},
    {'name': 'Agrykola', 'distance': 'Statue located in Warsaw Old Town Market Square'},
    {'name': 'Mongolian Military Museum', 'distance': 'Located in Ulaanbaatar city center'},
    {'name': 'Botanisk Hage og Museum', 'distance': 'Gardens and museum in central Oslo'},
    {'name': 'Parque Alcalá', 'distance': 'City park located in Pocitos area of Montevideo'},
    {'name': 'Parque de la 93', 'distance': 'Park located in trendy zone of Bogotá'},
    {'name': 'Parque El Virrey', 'distance': 'Park located in northern Bogotá suburbs'},
    {'name': 'Parque Cumbres de Curumo', 'distance': 'Natural area 15 km east of Caracas'},
    {'name': 'Fuente Plaza Venezuela', 'distance': 'Fountain located in public square in Caracas'},
    {'name': 'Constitution Hill', 'distance': 'Located northeast of Johannesburg city center'},
    {'name': 'Brickell Key Park', 'distance': 'Located on Brickell Key island east of downtown Miami'},
    {'name': 'National Museum of Kenya', 'distance': 'Located in central Nairobi'},
    {'name': 'Uhuru Gardens', 'distance': 'Located 5 km from Nairobi city center'},
    {'name': 'Phare D\'El Hank', 'distance': 'Lighthouse located on Cape El Hank, 25 km from Casablanca'},
    {'name': 'Hotel Central', 'distance': 'Located in central Cali'},
    {'name': 'Beit Beirut', 'distance': 'Museum located in Sodeco area of Beirut'},
    {'name': 'Gandhi Smriti', 'distance': 'Museum located in central Delhi'}, 
    {'name': 'Mongolian Natural History Museum', 'distance': 'Located in Ulaanbaatar city center'},
    {'name': 'Humayun’s Tomb', 'distance': 'Located in Nizamuddin area of Delhi'},
    {'name': 'Công Viên Thống Nhất', 'distance': 'Park located in Ho Chi Minh City center district'},
    {'name': 'Ho Chi Minh Mausoleum (Lăng Chủ Tịch Hồ Chí Minh (Ho Chi Minh Mausoleum))', 'distance': 'In Ba Đình Square, Hanoi city center'},
    {'name': 'Rizal Monument', 'distance': 'Located in Rizal Park in Manila'},
    {'name': 'Kilometer Zero', 'distance': 'Marker located in Intramuros, Manila'},
    {'name': 'Manila Bay', 'distance': 'Forms western edge of Manila city limits'},
    {'name': 'Pinaglabanan Shrine', 'distance': 'Located in San Juan city, Metro Manila'},
    {'name': 'Patung Kuda Arjuna Wiwaha', 'distance': 'Statue located in central Jakarta'},
    {'name': 'River of Life', 'distance': 'Waterfront located along Klang River in Kuala Lumpur'},
    {'name': 'Chicago Riverwalk', 'distance': 'Located along Chicago River in downtown area'},
    {'name': 'Grant Park - Butler Field', 'distance': 'Park located in Chicago city center'},
    {'name': 'Miami River Walk', 'distance': 'Located along Miami River in downtown Miami'},
    {'name': 'Boston Harborwalk', 'distance': 'Runs along harbor in downtown Boston area'},
    {'name': 'East Boston Greenway', 'distance': 'Linear park located in East Boston neighborhood'},
    {'name': 'Courtyard at Boston Public Library', 'distance': 'Located at central library in downtown Boston'},
    {'name': 'Chief Seattle Statue', 'distance': 'Located in Pioneer Square in downtown Seattle'},
    {'name': 'Discovery Children\'s Museum', 'distance': 'Located in Tacoma city center'},
    {'name': 'Lorenzi Park', 'distance': 'Located on the Las Vegas Strip'},
    {'name': 'Park at The Park', 'distance': 'Park located next to Petco Park in San Diego downtown'},
    {'name': 'The New Children\'s Museum', 'distance': 'Located in San Diego downtown'},
    {'name': 'Pantoja Park', 'distance': 'Small park located in central San Jose'}, 
    {'name': 'Tranquility Park', 'distance': 'Located in downtown Houston'},
    {'name': 'Reunion Park', 'distance': 'Park located in downtown Dallas'},
    {'name': 'Perot Museum of Nature and Science', 'distance': 'Museum located in downtown Dallas'},
    {'name': 'Martin Luther King, Jr. National Historic Site', 'distance': 'Located in Atlanta\'s Sweet Auburn neighborhood, 3 km from downtown'},
    {'name': 'Jackson Street Bridge', 'distance': 'Pedestrian bridge over South Platte River, located downtown Denver'},
    {'name': 'Denver Firefighters Museum', 'distance': 'Located in downtown Denver'},
    {'name': 'Denver Botanic Gardens', 'distance': 'Gardens located 6 km southeast of downtown Denver'},
    {'name': 'Children\'s Museum of Phoenix', 'distance': 'Located in downtown Phoenix'},
    {'name': 'Arizona Science Center', 'distance': 'Museum located downtown Phoenix'},
    {'name': 'The Icehouse', 'distance': 'Theater venue located in central Pasadena'},
    {'name': 'Oregon Museum of Science and Industry', 'distance': 'Located 4 km south of downtown Portland'},
    {'name': 'Salmon Street Springs Fountain', 'distance': 'Located in Tom McCall Waterfront Park, downtown Portland'},
    {'name': 'Hollywood Theatre', 'distance': 'Cinema located in central Portland'},
    {'name': 'khorgo', 'distance': 'Visitor center located in Khovsgol Nuur National Park, northern Mongolia'},
    {'name': 'The Franklin Institute', 'distance': 'Science museum located in Center City Philadelphia'},
    {'name': 'Washington Square', 'distance': 'Park located in downtown Philadelphia'}, 
    {'name': 'Independence National Historical Park', 'distance': 'Located in downtown Philadelphia'},
    {'name': 'Gastown Steam Clock', 'distance': 'Located in Gastown area of Vancouver'},
    {'name': 'Château Ramezay - Historic Site and Museum of Montreal', 'distance': 'Located in Old Montreal'},
    {'name': 'Calgary Tower', 'distance': 'Located downtown Calgary'},
    {'name': 'Major\'s Hill Park', 'distance': 'Located downtown Ottawa, near Parliament Hill'},
    {'name': 'Centennial Flame', 'distance': 'Monument located on Parliament Hill, Ottawa'},
    {'name': 'The zero point of Ulaanbaatar (Монгол улсын нийслэл Улаанбаатар хотын төв тэг цэг)', 'distance': 'Located in central Sukhbaatar Square, Ulaanbaatar'},
    {'name': 'Churchill Square', 'distance': 'Public square located downtown Edmonton'},
    {'name': 'Constable Ezio Faraone Park', 'distance': 'Small park located in Edmonton city center'},
    {'name': 'William Hawrelak Park', 'distance': 'Large park located 3 km northwest of Edmonton downtown'},
    {'name': 'Royal Alberta Museum', 'distance': 'Museum located in downtown Edmonton'},
    {'name': 'Louise McKinney Riverfront Park', 'distance': 'Located along riverfront in Edmonton downtown'},
    {'name': 'Adelaide Botanic Garden', 'distance': 'Located adjacent to Adelaide\'s northeast park lands'},
    {'name': 'National War Memorial', 'distance': 'Located downtown Ottawa, near Parliament Hill'},
    {'name': 'Riverbank Footbridge', 'distance': 'Pedestrian bridge crossing Red Deer River in downtown Calgary'},
    {'name': 'South Australian Museum', 'distance': 'Located on Adelaide\'s cultural boulevard, northwest edge of city center'},
    {'name': 'Bonython Park', 'distance': 'Located 2 km southwest of Adelaide city center'},
    {'name': 'Victoria Square/Tarndanyangga', 'distance': 'Public square located in Adelaide city center'},
    {'name': 'Veale Gardens', 'distance': 'Public gardens located adjacent Adelaide city center'},
    {'name': 'Skycity Sky Tower', 'distance': 'Located in central Auckland'},
    {'name': 'Albert Park', 'distance': 'Located 2 km southeast of central Auckland'},
    {'name': 'Silo Park', 'distance': 'Located on Auckland waterfront, just west of city center'},
    {'name': 'Auckland Domain', 'distance': 'Large park located 2 km southeast of city center'},
    {'name': 'Wintergarden', 'distance': 'Located in central Auckland, next to Aotea Square'},
    {'name': 'Takutai Square', 'distance': 'Public square located in central Auckland'},
    {'name': 'Aotea Square', 'distance': 'Public square located in central Auckland'},
    {'name': '185 Chairs Memorial', 'distance': 'Sculpture installation located at Otago University campus, Dunedin'},
    {'name': 'Emily Place Reserve', 'distance': 'Small reserve located in central Auckland'},
    {'name': 'Skydeck', 'distance': 'Observation deck located atop Sky Tower in central Auckland'},
    {'name': 'Christchurch Botanic Gardens', 'distance': 'Located adjacent Christchurch city center'},
    {'name': 'Margaret Mahy Family Playground', 'distance': 'Located in central Christchurch'},
    {'name': 'Christchurch Botanic Gardens Visitor Centre', 'distance': 'Located within botanic gardens in city center'},
    {'name': 'Victoria Square', 'distance': 'City square located in central Christchurch'},
    {'name': 'Riccarton House & Bush', 'distance': 'Located 5 km west from Christchurch city center'},
    {'name': 'Quake City', 'distance': 'Museum located just outside Christchurch city center'},
    {'name': 'Christchurch Cathedral Ruins', 'distance': 'Located in central Christchurch'},
    {'name': 'De Waal Park', 'distance': 'Park located near Camps Bay beach, 5 km from Cape Town center'},
    {'name': 'Lions Head Peak', 'distance': 'Summit located 6 km west of Cape Town center'},
    {'name': 'Innenhof der kaiserlichen Hofburg', 'distance': 'Courtyard located within the Hofburg Palace complex, central Vienna'},
    {'name': 'Berczy Park', 'distance': 'Located in downtown Toronto'},
    {'name': 'دار الكتب المصريه', 'distance': 'Located in central Cairo'},
    {'name': 'المعبد اليهودي', 'distance': 'Located in central Cairo'},
    {'name': 'Nobel Square', 'distance': 'Public square located along Lake'},
    {'name': 'Animals in War Memorial', 'distance': 'In central London, Hyde Park Corner'},
    {'name': 'The St Cecilia\'s Hall Museum of Instruments', 'distance': 'In Edinburgh city center'},
    {'name': 'University of Oxford Botanic Garden', 'distance': '1 km north of central Oxford'},
    {'name': 'Oxford University Museum of Natural History', 'distance': 'In central Oxford, near University Parks'},
    {'name': 'Madame Tussauds Sydney', 'distance': 'In Darling Harbour, 3 km west of Sydney CBD'},
    {'name': 'Cairns Marlin Marina', 'distance': 'In Cairns city center, on city waterfront'},
    {'name': 'Sydney Harbour Bridge', 'distance': 'In central Sydney, links the CBD to North Sydney'},
    {'name': 'Fundación Telefónica Argentina', 'distance': 'In Buenos Aires city center'},
    {'name': 'Cabildo de Buenos Aires', 'distance': 'On Plaza de Mayo, Buenos Aires city center'},
    {'name': 'Bariloche Moto Tours', 'distance': 'Located in San Carlos de Bariloche town center'},
    {'name': 'Reserva Biológica Bosque Nuboso Monteverde', 'distance': '10 km southeast of Santa Elena town'},
    {'name': 'Museo de Arte Indígena', 'distance': 'In Cusco historic center'}, 
    {'name': 'Salar de Uyuni', 'distance': '220 km southwest of Potosí, not located near major city'},
    {'name': 'Haifa City Museum', 'distance': 'At top of Carmel Center, 2 km south of Haifa center'},
    {'name': 'Independence Monument', 'distance': 'On principal avenue in Mexico City historic center'},
    {'name': 'Catarata Río Fortuna', 'distance': 'Within 5 km of La Fortuna town'},
    {'name': 'las gradas En san jose', 'distance': 'Outdoor steps venue in San Jose city center'},
    {'name': 'Parque México', 'distance': 'In hip Roma neighborhood, Mexico City'},
    {'name': 'Estación México', 'distance': 'Massive metro station in Cuauhtémoc borough, Mexico City'},
    {'name': 'Centro de Mérida', 'distance': 'In Mérida historic city center'},
    {'name': 'Siem Reap River', 'distance': 'Flows through center of Siem Reap'},
    {'name': 'Mirador del Valle de los Ingenios', 'distance': 'Overlooks the Valle de los Ingenios, 10 km from Trinidad'},
    {'name': 'Galle Maritime Museum', 'distance': 'Inside Galle Fort walls, in city center'},
    {'name': 'Indian ocean', 'distance': 'Coastline borders southwestern Sri Lanka'},
    {'name': 'Galle Clock Tower', 'distance': 'Inside Galle Fort, city center'}, 
    {'name': 'Galle Fort Beach', 'distance': 'Inside Galle Fort walls, city center'},
    {'name': 'Kandy Lake', 'distance': 'In center of Kandy city'}, 
    {'name': 'Colombo Lighthouse', 'distance': 'On southern edge of Colombo Port'},
    {'name': 'Golden Gate Bridge', 'distance': 'In San Francisco Bay connecting SF to Marin County'},
    {'name': 'Sacred City of Kandy', 'distance': 'Site includes central area of Kandy city'},
    {'name': 'Colombo Rowing Club', 'distance': 'In Colombo Fort district, city center'},
    {'name': 'Ella Rock', 'distance': '8 km hike from Ella village'},
    {'name': 'Agra Fort', 'distance': '3 km west of Taj Mahal in Agra'},
    {'name': 'Indian Agricultural Statistics Research Institute', 'distance': 'In Delhi metropolitan region, 20 km from city center'},
    {'name': 'The ghats of Varanasi', 'distance': 'Along banks of Ganges River in Varanasi city'},
    {'name': 'Phuket Wake Park Apartment', 'distance': '12 km northeast of Phuket town'},
    {'name': 'Dialogue in the Dark (บทเรียนในความมืด)', 'distance': 'In Siam Paragon mall, central Bangkok'},
    {'name': 'Palatial Gardens below Prague Castle (Palácové zahrady pod Pražským hradem)', 'distance': 'On the hill below Prague Castle, in the city center'},
    {'name': 'Santorini Camping', 'distance': 'Located in southern part of Santorini island, near Perissa'},
    {'name': 'Aarhus SeaRangers', 'distance': 'Meet at the harbor in Aarhus city center'},
    {'name': 'Inge Lehmann', 'distance': 'Statue located in central Copenhagen'},
    {'name': 'Reykjavíkurtjörn', 'distance': 'Pond located in Reykjavik city center'},
    {'name': 'MoMu - Fashion Museum Antwerp', 'distance': 'Located in Antwerp city center'},
    {'name': 'Prague Castle View Point (Vyhlídka na Hradčanském náměstí)', 'distance': 'Located in Prague Castle complex, city center'},
    {'name': 'Heidelberger Schloss', 'distance': 'Located above old town in Heidelberg city center'},
    {'name': 'Kijk In \'T Jat Brug', 'distance': 'Museum located in Bruges city center'},
    {'name': 'Denarau Golf and Racquet Club', 'distance': 'Located on Denarau Island by Nadi town'},
    {'name': 'Helsinki Sightseeing', 'distance': 'Boat tours leave from Helsinki city center harbor'},
    {'name': 'Macritchie Nature Trail', 'distance': 'Located within MacRitchie Reservoir Park in Singapore'},
    {'name': 'Bukit Timah Nature Reserve', 'distance': 'Located 10 km from Singapore city center'},
    {'name': 'Moderna Museet', 'distance': 'Museum located on Skeppsholmen island, central Stockholm'},
    {'name': 'Fotografiska', 'distance': 'Museum located in Södermalm district of Stockholm'},
    {'name': 'Várnegyed', 'distance': 'Section of Buda Castle complex in Budapest city center'},
    {'name': 'Filozófusok kertje', 'distance': 'Garden located within Budapest University campus'},
    {'name': 'Várkert Bazár', 'distance': 'Located below Buda Castle hill in Budapest center'},
    {'name': 'Park Kultury im. marszałka Edwarda Śmigłego-Rydza', 'distance': 'Park located in Lublin city center'},
    {'name': 'Agrykola', 'distance': 'Statue located in Warsaw Old Town Market Square'},
    {'name': 'Mongolian Military Museum', 'distance': 'Located in Ulaanbaatar city center'},
    {'name': 'Botanisk Hage og Museum', 'distance': 'Gardens and museum in central Oslo'},
    {'name': 'Parque Alcalá', 'distance': 'City park located in Pocitos area of Montevideo'},
    {'name': 'Parque de la 93', 'distance': 'Park located in trendy zone of Bogotá'},
    {'name': 'Parque El Virrey', 'distance': 'Park located in northern Bogotá suburbs'},
    {'name': 'Parque Cumbres de Curumo', 'distance': 'Natural area 15 km east of Caracas'},
    {'name': 'Fuente Plaza Venezuela', 'distance': 'Fountain located in public square in Caracas'},
    {'name': 'Constitution Hill', 'distance': 'Located northeast of Johannesburg city center'},
    {'name': 'Brickell Key Park', 'distance': 'Located on Brickell Key island east of downtown Miami'},
    {'name': 'National Museum of Kenya', 'distance': 'Located in central Nairobi'},
    {'name': 'Uhuru Gardens', 'distance': 'Located 5 km from Nairobi city center'}, 
    {'name': 'Phare D\'El Hank', 'distance': 'Lighthouse located on Cape El Hank, 25 km from Casablanca'},
    {'name': 'Hotel Central', 'distance': 'Located in central Cali'},
    {'name': 'Beit Beirut', 'distance': 'Museum located in Sodeco area of Beirut'},
    {'name': 'Gandhi Smriti', 'distance': 'Museum located in central Delhi'},
    {'name': 'Mongolian Natural History Museum', 'distance': 'Located in Ulaanbaatar city center'},
    {'name': 'Humayun’s Tomb', 'distance': 'Located in Nizamuddin area of Delhi'},
    {'name': 'Công Viên Thống Nhất', 'distance': 'Park located in Ho Chi Minh City center district'},
    {'name': 'Ho Chi Minh Mausoleum (Lăng Chủ Tịch Hồ Chí Minh (Ho Chi Minh Mausoleum))', 'distance': 'In Ba Đình Square, Hanoi city center'},
    {'name': 'Rizal Monument', 'distance': 'Located in Rizal Park in Manila'},
    {'name': 'Kilometer Zero', 'distance': 'Marker located in Intramuros, Manila'},
    {'name': 'Manila Bay', 'distance': 'Forms western edge of Manila city limits'},
    {'name': 'Pinaglabanan Shrine', 'distance': 'Located in San Juan city, Metro Manila'},
    {'name': 'Patung Kuda Arjuna Wiwaha', 'distance': 'Statue located in central Jakarta'},
    {'name': 'River of Life', 'distance': 'Waterfront located along Klang River in Kuala Lumpur'},
    {'name': 'Chicago Riverwalk', 'distance': 'Located along Chicago River in downtown area'},
    {'name': 'Grant Park - Butler Field', 'distance': 'Park located in Chicago city center'},
    {'name': 'Miami River Walk', 'distance': 'Located along Miami River in downtown Miami'},
    {'name': 'Boston Harborwalk', 'distance': 'Runs along harbor in downtown Boston area'},
    {'name': 'East Boston Greenway', 'distance': 'Linear park located in East Boston neighborhood'},
    {'name': 'Courtyard at Boston Public Library', 'distance': 'Located at central library in downtown Boston'},
    {'name': 'Chief Seattle Statue', 'distance': 'Located in Pioneer Square in downtown Seattle'},
    {'name': 'Discovery Children\'s Museum', 'distance': 'Located in Tacoma city center'},
    {'name': 'Lorenzi Park', 'distance': 'Located on the Las Vegas Strip'},
    {'name': 'Park at The Park', 'distance': 'Park located next to Petco Park in San Diego downtown'},
    {'name': 'The New Children\'s Museum', 'distance': 'Located in San Diego downtown'}, 
    {'name': 'Pantoja Park', 'distance': 'Small park located in central San Jose'},
    {'name': 'Tranquility Park', 'distance': 'Located in downtown Houston'},
    {'name': 'Reunion Park', 'distance': 'Park located in downtown Dallas'},
    {'name': 'Perot Museum of Nature and Science', 'distance': 'Museum located in downtown Dallas'},
    {'name': 'Martin Luther King, Jr. National Historic Site', 'distance': 'Located in Atlanta\'s Sweet Auburn neighborhood, 3 km from downtown'},
    {'name': 'Jackson Street Bridge', 'distance': 'Pedestrian bridge over South Platte River, located downtown Denver'},
    {'name': 'Denver Firefighters Museum', 'distance': 'Located in downtown Denver'},
    {'name': 'Denver Botanic Gardens', 'distance': 'Gardens located 6 km southeast of downtown Denver'},
    {'name': 'Children\'s Museum of Phoenix', 'distance': 'Located in downtown Phoenix'},
    {'name': 'Arizona Science Center', 'distance': 'Museum located downtown Phoenix'},
    {'name': 'The Icehouse', 'distance': 'Theater venue located in central Pasadena'},
    {'name': 'Oregon Museum of Science and Industry', 'distance': 'Located 4 km south of downtown Portland'},
    {'name': 'Salmon Street Springs Fountain', 'distance': 'Located in Tom McCall Waterfront Park, downtown Portland'},
    {'name': 'Hollywood Theatre', 'distance': 'Cinema located in central Portland'},
    {'name': 'khorgo', 'distance': 'Visitor center located in Khovsgol Nuur National Park, northern Mongolia'},
    {'name': 'The Franklin Institute', 'distance': 'Science museum located in Center City Philadelphia'},
    {'name': 'Washington Square', 'distance': 'Park located in downtown Philadelphia'},
    {'name': 'Independence National Historical Park', 'distance': 'Located in downtown Philadelphia'},
    {'name': 'Gastown Steam Clock', 'distance': 'Located in Gastown area of Vancouver'},
    {'name': 'Château Ramezay - Historic Site and Museum of Montreal', 'distance': 'Located in Old Montreal'},
    {'name': 'Calgary Tower', 'distance': 'Located downtown Calgary'},
    {'name': 'Major\'s Hill Park', 'distance': 'Located downtown Ottawa, near Parliament Hill'},
    {'name': 'Centennial Flame', 'distance': 'Monument located on Parliament Hill, Ottawa'},
    {'name': 'The zero point of Ulaanbaatar (Монгол улсын нийслэл Улаанбаатар хотын төв тэг цэг)', 'distance': 'Located in central Sukhbaatar Square, Ulaanbaatar'},
    {'name': 'Churchill Square', 'distance': 'Public square located downtown Edmonton'},
    {'name': 'Constable Ezio Faraone Park', 'distance': 'Small park located in Edmonton city center'},
    {'name': 'William Hawrelak Park', 'distance': 'Large park located 3 km northwest of Edmonton downtown'},
    {'name': 'Royal Alberta Museum', 'distance': 'Museum located in downtown Edmonton'},
    {'name': 'Louise McKinney Riverfront Park', 'distance': 'Located along riverfront in Edmonton downtown'},
    {'name': 'Adelaide Botanic Garden', 'distance': 'Located adjacent to Adelaide\'s northeast park lands'},
    {'name': 'National War Memorial', 'distance': 'Located downtown Ottawa, near Parliament Hill'},
    {'name': 'Riverbank Footbridge', 'distance': 'Pedestrian bridge crossing Red Deer River in downtown Calgary'},
    {'name': 'South Australian Museum', 'distance': 'Located on Adelaide\'s cultural boulevard, northwest edge of city center'},
    {'name': 'Bonython Park', 'distance': 'Located 2 km southwest of Adelaide city center'},
    {'name': 'Victoria Square/Tarndanyangga', 'distance': 'Public square located in Adelaide city center'},
    {'name': 'Veale Gardens', 'distance': 'Public gardens located adjacent Adelaide city center'},
    {'name': 'Skycity Sky Tower', 'distance': 'Located in central Auckland'},
    {'name': 'Albert Park', 'distance': 'Located 2 km southeast of central Auckland'},
    {'name': 'Silo Park', 'distance': 'Located on Auckland waterfront, just west of city center'},
    {'name': 'Auckland Domain', 'distance': 'Large park located 2 km southeast of city center'},
    {'name': 'Wintergarden', 'distance': 'Located in central Auckland, next to Aotea Square'},
    {'name': 'Takutai Square', 'distance': 'Public square located in central Auckland'},
    {'name': 'Aotea Square', 'distance': 'Public square located in central Auckland'},
    {'name': '185 Chairs Memorial', 'distance': 'Sculpture installation located at Otago University campus, Dunedin'},
    {'name': 'Emily Place Reserve', 'distance': 'Small reserve located in central Auckland'},
    {'name': 'Skydeck', 'distance': 'Observation deck located atop Sky Tower in central Auckland'},
    {'name': 'Christchurch Botanic Gardens', 'distance': 'Located adjacent Christchurch city center'},
    {'name': 'Margaret Mahy Family Playground', 'distance': 'Located in central Christchurch'},
    {'name': 'Christchurch Botanic Gardens Visitor Centre', 'distance': 'Located within botanic gardens in city center'},
    {'name': 'Victoria Square', 'distance': 'City square located in central Christchurch'},
    {'name': 'Riccarton House & Bush', 'distance': 'Located 5 km west from Christchurch city center'},
    {'name': 'Quake City', 'distance': 'Museum located just outside Christchurch city center'},
    {'name': 'Christchurch Cathedral Ruins', 'distance': 'Located in central Christchurch'},
    {'name': 'De Waal Park', 'distance': 'Park located near Camps Bay beach, 5 km from Cape Town center'},
    {'name': 'Lions Head Peak', 'distance': 'Summit located 6 km west of Cape Town center'},
    {'name': 'Innenhof der kaiserlichen Hofburg', 'distance': 'Courtyard located within the Hofburg Palace complex, central Vienna'},
    {'name': 'Berczy Park', 'distance': 'Located in downtown Toronto'},
    {'name': 'دار الكتب المصريه', 'distance': 'Located in central Cairo'},
    {'name': 'المعبد اليهودي', 'distance': 'Located in central Cairo'},
    {'name': 'Nobel Square', 'distance': 'Public square located along Lake'},
    {'name': 'Animals in War Memorial', 'distance': 'In central London, Hyde Park Corner'},
    {'name': 'The St Cecilia\'s Hall Museum of Instruments', 'distance': 'In Edinburgh city center'},
    {'name': 'University of Oxford Botanic Garden', 'distance': '1 km north of central Oxford'},
    {'name': 'Oxford University Museum of Natural History', 'distance': 'In central Oxford, near University Parks'},
    {'name': 'Madame Tussauds Sydney', 'distance': 'In Darling Harbour, 3 km west of Sydney CBD'},
    {'name': 'Cairns Marlin Marina', 'distance': 'In Cairns city center, on city waterfront'},
    {'name': 'Sydney Harbour Bridge', 'distance': 'In central Sydney, links the CBD to North Sydney'},
    {'name': 'Fundación Telefónica Argentina', 'distance': 'In Buenos Aires city center'},
    {'name': 'Cabildo de Buenos Aires', 'distance': 'On Plaza de Mayo, Buenos Aires city center'},
    {'name': 'Bariloche Moto Tours', 'distance': 'Located in San Carlos de Bariloche town center'},
    {'name': 'Reserva Biológica Bosque Nuboso Monteverde', 'distance': '10 km southeast of Santa Elena town'},
    {'name': 'Museo de Arte Indígena', 'distance': 'In Cusco historic center'},
    {'name': 'Salar de Uyuni', 'distance': '220 km southwest of Potosí, not located near major city'},
    {'name': 'Haifa City Museum', 'distance': 'At top of Carmel Center, 2 km south of Haifa center'},
    {'name': 'Independence Monument', 'distance': 'On principal avenue in Mexico City historic center'},
    {'name': 'Catarata Río Fortuna', 'distance': 'Within 5 km of La Fortuna town'},
    {'name': 'las gradas En san jose', 'distance': 'Outdoor steps venue in San Jose city center'},
    {'name': 'Parque México', 'distance': 'In hip Roma neighborhood, Mexico City'},
    {'name': 'Estación México', 'distance': 'Massive metro station in Cuauhtémoc borough, Mexico City'},
    {'name': 'Centro de Mérida', 'distance': 'In Mérida historic city center'},
    {'name': 'Siem Reap River', 'distance': 'Flows through center of Siem Reap'},
    {'name': 'Mirador del Valle de los Ingenios', 'distance': 'Overlooks the Valle de los Ingenios, 10 km from Trinidad'},
    {'name': 'Galle Maritime Museum', 'distance': 'Inside Galle Fort walls, in city center'},
    {'name': 'Indian ocean', 'distance': 'Coastline borders southwestern Sri Lanka'}, 
    {'name': 'Galle Clock Tower', 'distance': 'Inside Galle Fort, city center'},
    {'name': 'Galle Fort Beach', 'distance': 'Inside Galle Fort walls, city center'},
    {'name': 'Kandy Lake', 'distance': 'In center of Kandy city'},
    {'name': 'Colombo Lighthouse', 'distance': 'On southern edge of Colombo Port'},
    {'name': 'Golden Gate Bridge', 'distance': 'In San Francisco Bay connecting SF to Marin County'},
    {'name': 'Sacred City of Kandy', 'distance': 'Site includes central area of Kandy city'},
    {'name': 'Colombo Rowing Club', 'distance': 'In Colombo Fort district, city center'},
    {'name': 'Ella Rock', 'distance': '8 km hike from Ella village'},
    {'name': 'Agra Fort', 'distance': '3 km west of Taj Mahal in Agra'},
    {'name': 'Indian Agricultural Statistics Research Institute', 'distance': 'In Delhi metropolitan region, 20 km from city center'},
    {'name': 'The ghats of Varanasi', 'distance': 'Along banks of Ganges River in Varanasi city'},
    {'name': 'Phuket Wake Park Apartment', 'distance': '12 km northeast of Phuket town'},
    {'name': 'Dialogue in the Dark (บทเรียนในความมืด)', 'distance': 'In Siam Paragon mall, central Bangkok'},{'name': 'Palatial Gardens below Prague Castle (Palácové zahrady pod Pražským hradem)', 'distance': 'On the hill below Prague Castle, in the city center'},
    {'name': 'Santorini Camping', 'distance': 'Located in southern part of Santorini island, near Perissa'},
    {'name': 'Aarhus SeaRangers', 'distance': 'Meet at the harbor in Aarhus city center'},
    {'name': 'Inge Lehmann', 'distance': 'Statue located in central Copenhagen'},
    {'name': 'Reykjavíkurtjörn', 'distance': 'Pond located in Reykjavik city center'},
    {'name': 'MoMu - Fashion Museum Antwerp', 'distance': 'Located in Antwerp city center'},
    {'name': 'Prague Castle View Point (Vyhlídka na Hradčanském náměstí)', 'distance': 'Located in Prague Castle complex, city center'},
    {'name': 'Heidelberger Schloss', 'distance': 'Located above old town in Heidelberg city center'},
    {'name': 'Kijk In 'T Jat Brug', 'distance': 'Museum located in Bruges city center'},
    {'name': 'Denarau Golf and Racquet Club', 'distance': 'Located on Denarau Island by Nadi town'},
    {'name': 'Helsinki Sightseeing', 'distance': 'Boat tours leave from Helsinki city center harbor'},
    {'name': 'Macritchie Nature Trail', 'distance': 'Located within MacRitchie Reservoir Park in Singapore'},
    {'name': 'Bukit Timah Nature Reserve', 'distance': 'Located 10 km from Singapore city center'},
    {'name': 'Moderna Museet', 'distance': 'Museum located on Skeppsholmen island, central Stockholm'},
    {'name': 'Fotografiska', 'distance': 'Museum located in Södermalm district of Stockholm'},
    {'name': 'Várnegyed', 'distance': 'Section of Buda Castle complex in Budapest city center'},
    {'name': 'Filozófusok kertje', 'distance': 'Garden located within Budapest University campus'},
    {'name': 'Várkert Bazár', 'distance': 'Located below Buda Castle hill in Budapest center'},
    {'name': "Park Kultury im. marszałka Edwarda Śmigłego-Rydza", 'distance': "Park located in Lublin city center"},
    {'name': 'Agrykola', 'distance': 'Statue located in Warsaw Old Town Market Square'},
    {'name': 'Mongolian Military Museum', 'distance': 'Located in Ulaanbaatar city center'},
    {'name': 'Botanisk Hage og Museum', 'distance': 'Gardens and museum in central Oslo'},
    {'name': 'Parque Alcalá', 'distance': 'City park located in Pocitos area of Montevideo'},
    {'name': 'Parque de la 93', 'distance': 'Park located in trendy zone of Bogotá'},
    {'name': 'Parque El Virrey', 'distance': 'Park located in northern Bogotá suburbs'},
    {'name': 'Parque Cumbres de Curumo', 'distance': 'Natural area 15 km east of Caracas'},
    {'name': 'Fuente Plaza Venezuela', 'distance': 'Fountain located in public square in Caracas'},
    {'name': 'Constitution Hill', 'distance': 'Located northeast of Johannesburg city center'},
    {'name': 'Brickell Key Park', 'distance': 'Located on Brickell Key island east of downtown Miami'},
    {'name': 'National Museum of Kenya', 'distance': 'Located in central Nairobi'},
    {'name': 'Uhuru Gardens', 'distance': 'Located 5 km from Nairobi city center'},
    {'name': 'Phare D\'El Hank', 'distance': 'Lighthouse located on Cape El Hank, 25 km from Casablanca'},
    {'name': 'Hotel Central', 'distance': 'Located in central Cali'},
    {'name': 'Beit Beirut', 'distance': 'Museum located in Sodeco area of Beirut'},
    {'name': 'Gandhi Smriti', 'distance': 'Museum located in central Delhi'},
    {'name': 'Mongolian Natural History Museum', 'distance': 'Located in Ulaanbaatar city center'},
    {'name': 'Humayun’s Tomb', 'distance': 'Located in Nizamuddin area of Delhi'},
    {'name': 'Công Viên Thống Nhất', 'distance': 'Park located in Ho Chi Minh City center district'},
    {'name': 'Ho Chi Minh Mausoleum (Lăng Chủ Tịch Hồ Chí Minh (Ho Chi Minh Mausoleum))', 'distance': 'In Ba Đình Square, Hanoi city center'},
    {'name': 'Rizal Monument', 'distance': 'Located in Rizal Park in Manila'},
    {'name': 'Kilometer Zero', 'distance': 'Marker located in Intramuros, Manila'},
    {'name': 'Manila Bay', 'distance': 'Forms western edge of Manila city limits'},
    {'name': 'Pinaglabanan Shrine', 'distance': 'Located in San Juan city, Metro Manila'},
    {'name': 'Patung Kuda Arjuna Wiwaha', 'distance': 'Statue located in central Jakarta'},
    {'name': 'River of Life', 'distance': 'Waterfront located along Klang River in Kuala Lumpur'},
    {'name': 'Chicago Riverwalk', 'distance': 'Located along Chicago River in downtown area'},
    {'name': 'Grant Park - Butler Field', 'distance': 'Park located in Chicago city center'},
    {'name': 'Miami River Walk', 'distance': 'Located along Miami River in downtown Miami'},
    {'name': 'Boston Harborwalk', 'distance': 'Runs along harbor in downtown Boston area'},
    {'name': 'East Boston Greenway', 'distance': 'Linear park located in East Boston neighborhood'},
    {'name': 'Courtyard at Boston Public Library', 'distance': 'Located at central library in downtown Boston'},
    {'name': 'Chief Seattle Statue', 'distance': 'Located in Pioneer Square in downtown Seattle'},
    {'name': 'Discovery Children\'s Museum', 'distance': 'Located in Tacoma city center'},
    {'name': 'Lorenzi Park', 'distance': 'Located on the Las Vegas Strip'},
    {'name': 'Park at The Park', 'distance': 'Park located next to Petco Park in San Diego downtown'},
    {'name': 'The New Children\'s Museum', 'distance': 'Located in San Diego downtown'},
    {'name': 'Pantoja Park', 'distance': 'Small park located in central San Jose'},
    {'name': 'Tranquility Park', 'distance': 'Located in downtown Houston'},
    {'name': 'Reunion Park', 'distance': 'Park located in downtown Dallas'},
    {'name': 'Perot Museum of Nature and Science', 'distance': 'Museum located in downtown Dallas'},
    {'name': 'Martin Luther King, Jr. National Historic Site', 'distance': 'Located in Atlanta\'s Sweet Auburn neighborhood, 3 km from downtown'},
    {'name': 'Jackson Street Bridge', 'distance': 'Pedestrian bridge over South Platte River, located downtown Denver'},
    {'name': 'Denver Firefighters Museum', 'distance': 'Located in downtown Denver'},
    {'name': 'Denver Botanic Gardens', 'distance': 'Gardens located 6 km southeast of downtown Denver'},
    {'name': 'Children\'s Museum of Phoenix', 'distance': 'Located in downtown Phoenix'},
    {'name': 'Arizona Science Center', 'distance': 'Museum located downtown Phoenix'},
    {'name': 'The Icehouse', 'distance': 'Theater venue located in central Pasadena'},
    {'name': 'Oregon Museum of Science and Industry', 'distance': 'Located 4 km south of downtown Portland'},
    {'name': 'Salmon Street Springs Fountain', 'distance': 'Located in Tom McCall Waterfront Park, downtown Portland'},
    {'name': 'Hollywood Theatre', 'distance': 'Cinema located in central Portland'},
    {'name': 'khorgo', 'distance': 'Visitor center located in Khovsgol Nuur National Park, northern Mongolia'},
    {'name': 'The Franklin Institute', 'distance': 'Science museum located in Center City Philadelphia'},
    {'name': 'Washington Square', 'distance': 'Park located in downtown Philadelphia'},
    {'name': 'Independence National Historical Park', 'distance': 'Located in downtown Philadelphia'},
    {'name': 'Gastown Steam Clock', 'distance': 'Located in Gastown area of Vancouver'},
    {'name': 'Château Ramezay - Historic Site and Museum of Montreal', 'distance': 'Located in Old Montreal'},
    {'name': 'Calgary Tower', 'distance': 'Located downtown Calgary'},
    {'name': 'Major\'s Hill Park', 'distance': 'Located downtown Ottawa, near Parliament Hill'},
    {'name': 'Centennial Flame', 'distance': 'Monument located on Parliament Hill, Ottawa'},
    {'name': 'The zero point of Ulaanbaatar (Монгол улсын нийслэл Улаанбаатар хотын төв тэг цэг)', 'distance': 'Located in central Sukhbaatar Square, Ulaanbaatar'},
    {'name': 'Churchill Square', 'distance': 'Public square located downtown Edmonton'},
    {'name': 'Constable Ezio Faraone Park', 'distance': 'Small park located in Edmonton city center'},
    {'name': 'William Hawrelak Park', 'distance': 'Large park located 3 km northwest of Edmonton downtown'},
    {'name': 'Royal Alberta Museum', 'distance': 'Museum located in downtown Edmonton'},
    {'name': 'Louise McKinney Riverfront Park', 'distance': 'Located along riverfront in Edmonton downtown'},
    {'name': 'Adelaide Botanic Garden', 'distance': 'Located adjacent to Adelaide\'s northeast park lands'},
    {'name': 'National War Memorial', 'distance': 'Located downtown Ottawa, near Parliament Hill'},
    {'name': 'Riverbank Footbridge', 'distance': 'Pedestrian bridge crossing Red Deer River in downtown Calgary'},
    {'name': 'South Australian Museum', 'distance': 'Located on Adelaide\'s cultural boulevard, northwest edge of city center'},
    {'name': 'Bonython Park', 'distance': 'Located 2 km southwest of Adelaide city center'},
    {'name': 'Victoria Square/Tarndanyangga', 'distance': 'Public square located in Adelaide city center'},
    {'name': 'Veale Gardens', 'distance': 'Public gardens located adjacent Adelaide city center'},
    {'name': 'Skycity Sky Tower', 'distance': 'Located in central Auckland'},
    {'name': 'Albert Park', 'distance': 'Located 2 km southeast of central Auckland'},
    {'name': 'Silo Park', 'distance': 'Located on Auckland waterfront, just west of city center'},
    {'name': 'Auckland Domain', 'distance': 'Large park located 2 km southeast of city center'},
    {'name': 'Wintergarden', 'distance': 'Located in central Auckland, next to Aotea Square'},
    {'name': 'Takutai Square', 'distance': 'Public square located in central Auckland'},
    {'name': 'Aotea Square', 'distance': 'Public square located in central Auckland'},
    {'name': '185 Chairs Memorial', 'distance': 'Sculpture installation located at Otago University campus, Dunedin'},
    {'name': 'Emily Place Reserve', 'distance': 'Small reserve located in central Auckland'},
    {'name': 'Skydeck', 'distance': 'Observation deck located atop Sky Tower in central Auckland'},
    {'name': 'Christchurch Botanic Gardens', 'distance': 'Located adjacent Christchurch city center'},
    {'name': 'Margaret Mahy Family Playground', 'distance': 'Located in central Christchurch'},
    {'name': 'Christchurch Botanic Gardens Visitor Centre', 'distance': 'Located within botanic gardens in city center'},
    {'name': 'Victoria Square', 'distance': 'City square located in central Christchurch'},
    {'name': 'Riccarton House & Bush', 'distance': 'Located 5 km west from Christchurch city center'},
    {'name': 'Quake City', 'distance': 'Museum located just outside Christchurch city center'},
    {'name': 'Christchurch Cathedral Ruins', 'distance': 'Located in central Christchurch'},
    {'name': 'De Waal Park', 'distance': 'Park located near Camps Bay beach, 5 km from Cape Town center'},
    {'name': 'Lions Head Peak', 'distance': 'Summit located 6 km west of Cape Town center'},
    {'name': 'Innenhof der kaiserlichen Hofburg', 'distance': 'Courtyard located within the Hofburg Palace complex, central Vienna'},
    {'name': 'Berczy Park', 'distance': 'Located in downtown Toronto'},
    {'name': 'دار الكتب المصريه', 'distance': 'Located in central Cairo'},
    {'name': 'المعبد اليهودي', 'distance': 'Located in central Cairo'},
    {'name': 'Nobel Square', 'distance': 'Public square located along Lake'},
    {'name': 'Animals in War Memorial', 'distance': 'In central London, Hyde Park Corner'},
    {'name': 'The St Cecilia\'s Hall Museum of Instruments', 'distance': 'In Edinburgh city center'},
    {'name': 'University of Oxford Botanic Garden', 'distance': '1 km north of central Oxford'},
    {'name': 'Oxford University Museum of Natural History', 'distance': 'In central Oxford, near University Parks'},
    {'name': 'Madame Tussauds Sydney', 'distance': 'In Darling Harbour, 3 km west of Sydney CBD'},
    {'name': 'Cairns Marlin Marina', 'distance': 'In Cairns city center, on city waterfront'},
    {'name': 'Sydney Harbour Bridge', 'distance': 'In central Sydney, links the CBD to North Sydney'},
    {'name': 'Fundación Telefónica Argentina', 'distance': 'In Buenos Aires city center'},
    {'name': 'Cabildo de Buenos Aires', 'distance': 'On Plaza de Mayo, Buenos Aires city center'},
    {'name': 'Bariloche Moto Tours', 'distance': 'Located in San Carlos de Bariloche town center'},
    {'name': 'Reserva Biológica Bosque Nuboso Monteverde', 'distance': '10 km southeast of Santa Elena town'},
    {'name': 'Museo de Arte Indígena', 'distance': 'In Cusco historic center'},
    {'name': 'Salar de Uyuni', 'distance': '220 km southwest of Potosí, not located near major city'},
    {'name': 'Haifa City Museum', 'distance': 'At top of Carmel Center, 2 km south of Haifa center'},
    {'name': 'Independence Monument', 'distance': 'On principal avenue in Mexico City historic center'},
    {'name': 'Catarata Río Fortuna', 'distance': 'Within 5 km of La Fortuna town'},
    {'name': 'las gradas En san jose', 'distance': 'Outdoor steps venue in San Jose city center'},
    {'name': 'Parque México', 'distance': 'In hip Roma neighborhood, Mexico City'},
    {'name': 'Estación México', 'distance': 'Massive metro station in Cuauhtémoc borough, Mexico City'},
    {'name': 'Centro de Mérida', 'distance': 'In Mérida historic city center'},
    {'name': 'Siem Reap River', 'distance': 'Flows through center of Siem Reap'},
    {'name': 'Mirador del Valle de los Ingenios', 'distance': 'Overlooks the Valle de los Ingenios, 10 km from Trinidad'},
    {'name': 'Galle Maritime Museum', 'distance': 'Inside Galle Fort walls, in city center'},
    {'name': 'Indian ocean', 'distance': 'Coastline borders southwestern Sri Lanka'},
    {'name': 'Galle Clock Tower', 'distance': 'Inside Galle Fort, city center'},
    {'name': 'Galle Fort Beach', 'distance': 'Inside Galle Fort walls, city center'},
    {'name': 'Kandy Lake', 'distance': 'In center of Kandy city'},
    {'name': 'Colombo Lighthouse', 'distance': 'On southern edge of Colombo Port'},
    {'name': 'Golden Gate Bridge', 'distance': 'In San Francisco Bay connecting SF to Marin County'},
    {'name': 'Sacred City of Kandy', 'distance': 'Site includes central area of Kandy city'},
    {'name': 'Colombo Rowing Club', 'distance': 'In Colombo Fort district, city center'},
    {'name': 'Ella Rock', 'distance': '8 km hike from Ella village'},
    {'name': 'Agra Fort', 'distance': '3 km west of Taj Mahal in Agra'},
    {'name': 'Indian Agricultural Statistics Research Institute', 'distance': 'In Delhi metropolitan region, 20 km from city center'},
    {'name': 'The ghats of Varanasi', 'distance': 'Along banks of Ganges River in Varanasi city'},
    {'name': 'Phuket Wake Park Apartment', 'distance': '12 km northeast of Phuket town'},
    {'name': 'Dialogue in the Dark (บทเรียนในความมืด)', 'distance': 'In Siam Paragon mall, central Bangkok'},]